### ISSUE TITLE
Stencil Weight Matrix Issue 

### ISSUE THREAD

**Issue by neozhang307** [HPHEX/LoRAStencil#1]
2dstar3r, 2dbox1r and 2dbox3r. I suspect it is due to the current example input is not low-rank decomposable, (can you handle general stencil weight?), or maybe I just implemented a CPU version code incorrectly.

Recommended Actions
change the current weight matrix inside the code to be low-rank decomposable
Add unit tests to validate output correctness, e.g. CPU stencil implementation.

**Comment by zondie17** [comment]
Thank you for your insightful feedback. We have updated the weight matrix and added a correctness check function for all cases, and the code now runs smoothly.

**Comment by neozhang307** [comment]
Thanks a lot! I think the issue is resolved
